# ~/.config/starship/default.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Votre configuration personnelle dÃ©taillÃ©e
# Par exemple, avec des icÃ´nes, des couleurs subtiles, etc.
[username]
show_always = true
style_user = "blue bold"

[directory]
style = "cyan"

[git_branch]
symbol = "ğŸŒ± "

[character]
success_symbol = '[â¯](bold green) '
error_symbol = '[âœ—](bold red) '